name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  deskpro_ui:
    name: Test / Build
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build package
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm exec tsc -b

      - name: Run tests
        run: pnpm run test

      - name: Build Storybook
        run: pnpm run build:storybook

      - name: Deploy Storybook
        id: chromauideployment
        if: github.actor != 'dependabot[bot]'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook
          exitOnceUploaded: true

      - name: Leave comment with URL
        if: github.actor != 'dependabot[bot]'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Storybook build URL ${{steps.chromauideployment.outputs.storybookUrl}}

            Chromatic URL ${{steps.chromauideployment.outputs.buildUrl}}
